export const IMAGE_SRC = {
    PLAYER: ["images/SpaceshipV3.1.png",
        "images/SpaceshipV3.2.png",
        "images/SpaceshipV3.3.png",
        "images/SpaceshipV3.4.png",
        "images/SpaceshipV3.5.png",
        "images/SpaceshipV3.hit.png"],
    ENEMY: ["images/EnemySpaceshipV1.1.png",
        "images/EnemySpaceshipV1.2.png",
        "images/EnemySpaceshipV1.3.png",
        "images/EnemySpaceshipV1.4.png",
        "images/EnemySpaceshipV1.5.png",
        "images/EnemySpaceshipV1.hit.png"],
    PROJECTILES: ["images/Blaster.png",
        "images/MissileProjectile.png",
        "images/ExplosionV1.png",
        "images/ExplosionV2.png",
        "images/ExplosionV3.png"],
    UI: ["images/HealthBarDisplay.png", 
        "images/ShieldBarDisplay.png", 
        "images/UpArrow.png", 
        "images/DownArrow.png", 
        "images/FireButton.png", 
        "images/MissileButton.png",
        "images/PauseButton.png"
    ]
};